const char *help_text[] = { 
"PATTERN \n \nA+LEFT/RIGHT = CHANGE PITCH \nB+LEFT/RIGHT = CHANGE PAN \nA+UP/DOWN = CHANGE VELOCITY \nB+A = DELETE CELL \nL/R = CHANGE CURRENT PATTERN \nSTART = PLAY/STOP PATTERN/SONG \nA+R = COPY PATTERN \nA+L = PASTE PATTERN \nSEL + A = CUT PATTERN \nSEL+B = RANDOM PATTERN \nSEL+DOWN = SOLO/UNSOLO CHANNEL \nSEL+UP = MUTE/UNMUTE CHANNEL \n \nSEL+L = CHANGE SCREEN", 

"SONG \n \nA+LEFT/RIGHT/UP/DOWN = \nCHANGE ORDER \nSEL+A = PASTE ORDER \nB+A = CUT ORDER \nL/R = CHANGE ORDER SCREEN \nSTART = START PLAYING/\nQUEUE CHAIN \nSEL+START = STOP PLAYING \n \nSEL+L/R = CHANGE SCREEN", 

"SAMPLES \n \nLEFT/RIGHT/UP/DOWN = \nMOVE CURSOR \n \nA = MENU ACTION \nSEL+B = RANDOMISE \n \nSEL+L/R = CHANGE SCREEN",

"SETTINGS \n \nLEFT/RIGHT/UP/DOWN = \nMOVE CURSOR \n \nA = MENU ACTION \n \nSEL+L = CHANGE SCREEN" };
